import 'dotenv/config'
import { PrismaClient, BlockType, Brand } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Create admin users
  const adminPassword = await bcrypt.hash('admin123', 10)

  const admin = await prisma.user.upsert({
    where: { email: 'admin@boommarketing.hu' },
    update: {},
    create: {
      email: 'admin@boommarketing.hu',
      passwordHash: adminPassword,
      name: 'Boom Admin',
      role: 'SUPER_ADMIN',
    },
  })

  const admin2 = await prisma.user.upsert({
    where: { email: 'admin@aiboost.hu' },
    update: {},
    create: {
      email: 'admin@aiboost.hu',
      passwordHash: adminPassword,
      name: 'AiBoost Admin',
      role: 'ADMIN',
    },
  })

  console.log('✅ Created admin users')

  // Block Templates
  const blockTemplates = [
    {
      blockType: BlockType.HERO,
      name: 'Standard Hero',
      description: 'Teljes szélességű hero háttérképpel és CTA-val',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Árajánlat {{clientName}} részére',
        subheading: 'Modern marketing megoldások vállalkozásoknak',
        backgroundImage: '/images/hero-bg.jpg',
        ctaText: 'Kezdjünk neki',
        ctaUrl: '#contact',
        alignment: 'center',
      },
      displayOrder: 1,
    },
    {
      blockType: BlockType.VALUE_PROP,
      name: '2 Oszlopos Értékajánlat',
      description: 'Értékajánlat 2 oszlopban középső ikonnal',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Miben nyújtunk többet?',
        leftColumn: {
          title: 'Előnyeink',
          items: [
            'Transzparens kommunikáció',
            'Folyamatos optimalizálás',
            'Fix árazás, jutalék mentesen',
            'Havi riport találkozó',
          ],
        },
        rightColumn: {
          title: 'A mi hitvallásunk',
          content: 'Úgy gondoljuk, hogy a sikeres marketing az őszinte partneri kapcsolaton alapul.',
        },
        iconUrl: '/images/value-icon.svg',
      },
      displayOrder: 2,
    },
    {
      blockType: BlockType.PLATFORM_FEATURES,
      name: 'Platform Funkciók',
      description: 'Platform logó és bullet pontok',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        platformName: 'Google Ads',
        platformLogo: '/logos/google-ads.svg',
        heading: 'Google PPC Hirdetéskezelés',
        features: [
          'Keresőhálózati kampányok',
          'Display hálózati hirdetések',
          'Shopping kampányok',
          'YouTube video hirdetések',
          'Remarketing kampányok',
        ],
        description: 'Teljes körű Google Ads kampánykezelés átfogó riportolással és folyamatos optimalizálással.',
        backgroundColor: '#4285f4',
      },
      displayOrder: 3,
    },
    {
      blockType: BlockType.PRICING_TABLE,
      name: '3 Oszlopos Árazás',
      description: 'Háromoszlopos árazási tábla kedvezménnyel',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Válaszd ki a csomagod',
        description: 'Minden csomag tartalmazza a teljes körű kampánykezelést és havi riportolást.',
        plans: [
          {
            id: '1',
            name: 'Meta PPC',
            description: 'Facebook és Instagram hirdetések',
            originalPrice: null,
            discountedPrice: 169990,
            currency: 'HUF',
            billingPeriod: 'monthly',
            features: [
              'Facebook hirdetések',
              'Instagram kampányok',
              'Kreatív gyártás',
              'Havi riport találkozó',
            ],
            isPopular: false,
            ctaText: 'Kezdjük el',
          },
          {
            id: '2',
            name: 'Google + Meta',
            description: 'Kombinált kampánykezelés',
            originalPrice: 305820,
            discountedPrice: 271660,
            currency: 'HUF',
            billingPeriod: 'monthly',
            features: [
              'Minden Meta funkció',
              'Google Ads kezelés',
              'Remarketing kampányok',
              'Havi stratégiai konzultáció',
            ],
            isPopular: true,
            ctaText: 'Kezdjük el',
          },
          {
            id: '3',
            name: 'Full Package',
            description: 'Teljes körű marketing megoldás',
            originalPrice: null,
            discountedPrice: 450000,
            currency: 'HUF',
            billingPeriod: 'monthly',
            features: [
              'Minden előző funkció',
              'TikTok hirdetések',
              'E-mail marketing',
              'Landing oldal készítés',
            ],
            isPopular: false,
            ctaText: 'Egyeztetés',
          },
        ],
      },
      displayOrder: 4,
    },
    {
      blockType: BlockType.GUARANTEES,
      name: 'Garanciák',
      description: '3 oszlopos garancia szekció',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Mire számíthatsz?',
        leftColumn: [
          '2 munkanapon belüli e-mail válaszidő',
          '3 munkanapon belüli reakció módosítási kérésekre',
          '4 munkanapon belül kampány módosítások',
        ],
        rightColumn: [
          'Fix árazás, nincs jutalék',
          'Minimum 3 hónapos együttműködés',
          'Havi részletes riportolás',
        ],
        centerImage: '/images/guarantees.svg',
      },
      displayOrder: 5,
    },
    {
      blockType: BlockType.PROCESS_TIMELINE,
      name: 'Folyamat Timeline',
      description: 'Lépésről lépésre folyamat megjelenítése',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Hogyan működünk együtt?',
        steps: [
          {
            id: '1',
            title: '1. Hónap',
            subtitle: 'Felkészülés',
            description: 'Stratégia egyeztetés, kampány setup, kreatív gyártás',
          },
          {
            id: '2',
            title: '2. Hónap',
            subtitle: 'Indítás',
            description: 'Kampányok indítása, tesztelés, első optimalizálások',
          },
          {
            id: '3',
            title: '3. Hónap',
            subtitle: 'Optimalizálás',
            description: 'Finomhangolás, skálázás, A/B tesztek',
          },
          {
            id: '4',
            title: '4+ Hónap',
            subtitle: 'Növekedés',
            description: 'Folyamatos fejlesztés és eredményközpontú működés',
          },
        ],
      },
      displayOrder: 6,
    },
    {
      blockType: BlockType.CLIENT_LOGOS,
      name: 'Ügyfél Logók',
      description: 'Grid elrendezésű logó showcase',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Partnereink',
        logos: [
          { id: '1', url: '/logos/client-1.png', alt: 'Ügyfél 1' },
          { id: '2', url: '/logos/client-2.png', alt: 'Ügyfél 2' },
          { id: '3', url: '/logos/client-3.png', alt: 'Ügyfél 3' },
          { id: '4', url: '/logos/client-4.png', alt: 'Ügyfél 4' },
          { id: '5', url: '/logos/client-5.png', alt: 'Ügyfél 5' },
          { id: '6', url: '/logos/client-6.png', alt: 'Ügyfél 6' },
        ],
        columns: 3,
      },
      displayOrder: 7,
    },
    {
      blockType: BlockType.SERVICES_GRID,
      name: 'Szolgáltatások Grid',
      description: 'Kártyák elrendezésben szolgáltatások',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'További szolgáltatásaink',
        services: [
          {
            id: '1',
            title: 'E-mail Marketing',
            description: 'Automatizált e-mail kampányok, szegmentálás, reportolás',
            icon: '/icons/email.svg',
            price: '450.000 Ft',
          },
          {
            id: '2',
            title: 'Landing Oldal',
            description: 'Konverzióra optimalizált landing oldalak tervezése és kivitelezése',
            icon: '/icons/landing.svg',
            price: '350.000 Ft',
          },
          {
            id: '3',
            title: 'Tartalomgyártás',
            description: 'Blogcikkek, hírlevél tartalmak, social media posztok',
            icon: '/icons/content.svg',
            price: '35.000 Ft/db',
          },
        ],
        columns: 3,
      },
      displayOrder: 8,
    },
    {
      blockType: BlockType.TEXT_BLOCK,
      name: 'Szöveges Blokk',
      description: 'Egyszerű szöveges tartalom',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Részletek',
        content: 'Itt helyezhetsz el bármilyen kiegészítő információt, részletes leírást vagy magyarázatot.',
      },
      displayOrder: 9,
    },
    {
      blockType: BlockType.TWO_COLUMN,
      name: 'Két Oszlop',
      description: 'Kép és szöveg kombinált layout',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        imageUrl: '/images/placeholder.jpg',
        imageSide: 'left',
        heading: 'Miért válassz minket?',
        content: 'Több mint 5 éves tapasztalat a digitális marketingben. Segítettünk már 100+ ügyfélnek növelni online jelenlétüket.',
        ctaText: 'Tudj meg többet',
        ctaUrl: '#contact',
      },
      displayOrder: 10,
    },
    {
      blockType: BlockType.CTA,
      name: 'Call-to-Action',
      description: 'Felhívás cselekvésre szekció',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Készen állsz az indulásra?',
        description: 'Kérj egyedi ajánlatot vagy egyeztess velünk egy ingyenes konzultáción.',
        primaryCta: {
          text: 'Ajánlat kérés',
          url: '#contact',
        },
        secondaryCta: {
          text: 'Konzultáció foglalás',
          url: '#meeting',
        },
        backgroundImage: '/images/cta-bg.jpg',
        backgroundColor: '#fa604a',
      },
      displayOrder: 11,
    },
    {
      blockType: BlockType.STATS,
      name: 'Statisztikák',
      description: 'Számok és eredmények megjelenítése',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Eredményeink számokban',
        stats: [
          {
            id: '1',
            value: '100+',
            label: 'Elégedett ügyfél',
          },
          {
            id: '2',
            value: '5+',
            label: 'Év tapasztalat',
          },
          {
            id: '3',
            value: '250%',
            label: 'Átlagos ROI',
          },
          {
            id: '4',
            value: '24/7',
            label: 'Támogatás',
          },
        ],
      },
      displayOrder: 12,
    },
    // NEW BOOM TEMPLATES START HERE (displayOrder 100+)
    {
      blockType: BlockType.HERO,
      name: 'BOOM Árajánlat Cover 2025',
      description: 'BOOM márkaidentitás szerinti hero blokk - Page 1',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        headingPrefix: 'Árajánlat',
        headingMain: '{{clientName}}',
        headingSuffix: 'részére',
        subheading: 'Készítette: {{createdByName}} | 2025',
        createdByPrefix: 'Készítette',
        createdByName: '{{createdByName}}',
        backgroundImage: '/images/boom/hero-meeting-bg.jpg',
        alignment: 'left',
        ctaText: 'Kezdjünk bele!',
        ctaUrl: '#services',
      },
      displayOrder: 100,
    },
    {
      blockType: BlockType.VALUE_PROP,
      name: 'BOOM Filozófia és Előnyök',
      description: 'Miben nyújtunk többet - Marketing Ökoszisztéma hitvallás - Page 2',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Miben nyújtunk többet?',
        subheading: 'BOOM Marketing hitvallása',
        leftColumn: {
          title: 'Miben nyújtunk többet?',
          items: [
            '7 év szakértői tapasztalat',
            'Adatokra alapozzuk a döntéseinket',
            '48 órán belül válaszolunk',
            'Brand specifikus kampányok',
            'Fix áron dolgozunk, jutalékmentesen',
            'Senior kollégák kezelik a projekteket',
            'Heti legfeljebb 2 új projektet vállalunk be',
            'Évi 11 hónapban fogadunk új ügyfeleket',
            'Nem csak riportokat küldünk, hanem havonta leülünk, beszélgetünk, ötletelünk',
          ],
        },
        rightColumn: {
          title: 'BOOM Marketing hitvallása',
          content: 'Marketingre mindenkinek szüksége van, de fizetett hirdetésekre nem feltétlenül. Vannak olyan esetek, amikor már be kell hozni, de olyan is, amikor még nem kell ezzel foglalkozni. Mi Marketing Ökoszisztémában gondolkodunk.',
          subtitle: '"Marketing ökoszisztéma":',
          quote: '"Olyan marketing rendszer, ahol a benne foglalt elemek nem egymást kannibalizálva, hanem egymást segítve működnek."',
        },
        centerImage: '/images/boom/ecosystem-illustration.png',
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 101,
    },
    {
      blockType: BlockType.TWO_COLUMN,
      name: 'Marketing Ökoszisztéma Magyarázat',
      description: 'Miért legyen egy kézben a marketing rendszered - Marketinges eszköztára - Page 3',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Miért legyen egy kézben a marketing rendszered?',
        subheading: 'Marketinges eszköztára',
        imageUrl: '/images/boom/ecosystem-diagram.png',
        imageSide: 'right',
        leftColumn: {
          title: 'Miért legyen egy kézben a marketing rendszered?',
          items: [
            'Dinamikus kapcsolattartás',
            'Egymást segítő csatornák és kampányok',
            'Egyensúlyba kerülnek az elemek',
            'Hatékonyabb hirdetések',
            'Folyamatos skálázhatóság',
            'Biztonságosabb, nincs egy platform változásainak kiszolgáltatva a céged',
          ],
        },
        rightColumn: {
          title: 'Marketinges eszköztára',
          items: [
            'Egy jó marketinges olyan, mint egy profi szakács',
            'Minél több eszköz áll rendelkezésre annál finomabb ételeket tud főzni',
            'Vegyük példának az alábbit:',
            'Egy Tik-Tok, Facebook és weboldal hármasból kombinált kampányokat tud készíteni',
            'Tik-Tokon alacsony kattintási költségért oldallátogatókat terel a weboldalra, és a látogatókra a Facebookon visszacélozva fog eladni',
            'Bármelyik eleme hiányzik a szakácsnak, ezt ez ételt nem tudja elkészíteni, csak megközelíteni tudná azt',
            'Az ökoszisztéma elemei egymást segítve hoznak létre hatékonyabb kommunikációt',
          ],
        },
        caseStudy: {
          text: 'Az egyik ügyfelünk Meta kampányait kezeltük 12x megtérülés mellett, amikor egyik nap csökkenni kezdtek a számok, drasztikusan. Utólag derült ki, hogy a Google kampányait kezelő másik csapat retargeting kampánya lemásolta a mi kampányinkat, így elvonta a figyelmet a Meta kampányokról, teljesen felbomlott az addig jól működő rendszer. Ha egy kézben lett volna a két platform, akkor egyensúly megtartása mellett, összehangolt kommunikációval hatékonyabb működést lehetett volna elérni. Később át is vettük a Google-t is, hogy ez többet ne történhessen meg.',
        },
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 102,
    },
    {
      blockType: BlockType.PLATFORM_FEATURES,
      name: 'Meta PPC Platform',
      description: 'Meta (Facebook, Instagram) PPC részletek - Page 4',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        platformName: 'Meta PPC',
        platformLogo: '/logos/meta-logo.svg',
        heading: 'Meta PPC',
        features: [
          'Több platform egyidejűleg elérhető',
          'Célcsoport alapján történő célzás',
          'Ez A hirdetési felület',
          'Itt érhető el a legnagyobb közönség',
          'Könnyen elindítható',
          'Extra költséget nem igényelnek a kampányok',
        ],
        description: 'Az indulása óta a Meta platform a fizetett hirdetési platformok koronázatlan királya. A mai napig itt érhető el a legtöbb ember. A többi hirdetési felülethez képest jóval egyszerűbb elindulni itt, statikus kreatívokkal vagy termékkatalógussal már indíthatóak is a kampányok. Több platform (Facebook, Instagram) egyidejű kezelése elérhető egy felületről.',
        backgroundColor: '#4267B2',
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 103,
    },
    {
      blockType: BlockType.PLATFORM_FEATURES,
      name: 'Google Ads Platform',
      description: 'Google Ads keresési platform részletek - Page 5',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        platformName: 'Google',
        platformLogo: '/logos/google-logo.svg',
        heading: 'Google Keresés',
        features: [
          'Kulcsszavak alapján történő célzás',
          'A legidősebb hirdetési felület',
          'Könnyű pénz',
          'Közvetlen igényre reagálunk',
          'Nincs extra költsége a kampányoknak',
          'Tapasztalat és tudás szükséges hozzá',
          'Bonyolultabb és nehezebb rajta elindulni',
        ],
        description: 'A legidősebb hirdetési platform, ahol a vásárlói útvonal más részét érjük el, mint a többi felületen. Itt közvetlenül egy igényre reagálunk és nem mi keltjük fel azt, mint a többi felület esetén. Nincs extra költsége, mint egy TikTok fióknak. Technikai platform, ahol a megfelelő kulcsszavakkal történő célzás nagy szaktudást és tapasztalatot igényel, ezért nehezebb elindulni rajta.',
        backgroundColor: '#4285F4',
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 104,
    },
    {
      blockType: BlockType.PLATFORM_FEATURES,
      name: 'TikTok Platform',
      description: 'TikTok hirdetési platform részletek - Page 6',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        platformName: 'TikTok',
        platformLogo: '/logos/tiktok-logo.svg',
        heading: 'TikTok',
        features: [
          'Még viszonylag olcsó hirdetési felület',
          'Kisebb a verseny, mert magasabb a belépési küszöb',
          'Fiatal közönséget hatékonyan érhetünk el',
          'Minden célcsoport megtalálható a fiatalok mellett is',
          'Extra költségként a videógyártás merül fel',
          'Nagyobb a belépési küszöb, ami a versenyt is csökkenti',
        ],
        description: 'Ez a platform viszonylag még telítetlen, kisebb rajta a verseny, így a díjak is kedvezőbbek, mint a nagyobb testvéreiken. A platformon minden célcsoport elérhető, de a fiatal közönséget hatékonyabban lehet elérni itt. Az induláshoz szükséges videós tartalmakat gyártani, ami extra költséget jelent a többi platformhoz képest, viszont ezek a videós anyagok több platformon is felhasználhatóak (gyakran erősítik például a Facebookot is).',
        backgroundColor: '#000000',
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 105,
    },
    {
      blockType: BlockType.PRICING_TABLE,
      name: 'BOOM Ökoszisztéma Árazás - 3 Platform',
      description: 'Marketing ökoszisztéma építése árazási táblázat - Pages 7-8',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Ökoszisztéma építése:',
        description: 'A szolgáltatás ára az alapján változik, hogy mennyi platformot kezelünk. A grafikusi és kampánykezeléssel kapcsolatos munkát teljeskörűen vállaljuk egy összegen belül. Ez azt jelenti, hogy nincs felső értékhatára a kezelt kampányoknak, ezt mindig az határozza meg, hogy mekkora marketing budgettel dolgozunk.',
        plans: [
          {
            id: '1',
            name: '1. Platform',
            description: 'Egy választott platform kezelése',
            originalPrice: null,
            discountedPrice: 169990,
            currency: 'HUF',
            billingPeriod: 'monthly',
            features: [
              'Választható platformok:',
              'Google',
              'Meta',
              'LinkedIn',
              'Criteo',
              'Pinterest',
              'Youtube',
            ],
            isPopular: false,
            ctaText: 'Kezdjük el',
          },
          {
            id: '2',
            name: '2. Platform',
            description: 'Két választott platform kezelése',
            originalPrice: null,
            discountedPrice: 135830,
            currency: 'HUF',
            billingPeriod: 'monthly',
            features: [
              'Választható platformok:',
              'TikTok',
              'Google',
              'Meta',
              'LinkedIn',
              'Criteo',
              'Pinterest',
              'Youtube',
            ],
            isPopular: true,
            ctaText: 'Kezdjük el',
          },
          {
            id: '3',
            name: '3. Platform',
            description: 'Három választott platform kezelése',
            originalPrice: null,
            discountedPrice: 135830,
            currency: 'HUF',
            billingPeriod: 'monthly',
            features: [
              'Választható platformok:',
              'TikTok',
              'Google',
              'Meta',
              'LinkedIn',
              'Criteo',
              'Pinterest',
              'Youtube',
            ],
            isPopular: false,
            ctaText: 'Kezdjük el',
          },
        ],
        note1: 'Hogyan éri ez meg nekünk?',
        note1Description: 'Az évek alatt az láttuk, hogy azoknak az ügyfeleinknek, akiknek minimum 2 platformot kezelünk jobban fejlődik a cége. Marketingesként jobban tudunk kommunikálni, viszont nem kerül 2x annyi munkába az együttműködés, mint 1 db platform esetén, így kedvezményt tudunk adni a további platformokból.',
        note2: 'Hiszünk a hosszútávú együttműködésben, ezért átlátható fix árakon dolgozunk, jutalékmentesen.',
        note2Description: 'A piacon átlagban 5-10% között kérnek el a hirdetési költségből származó jutalékot, de mi a rendszerek építésében látjuk a win-win teremtő helyzetet, nem a jutalékokban.',
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 106,
    },
    {
      blockType: BlockType.SERVICES_GRID,
      name: 'BOOM Bónusz Szolgáltatások',
      description: 'Díjmentes bónusz szolgáltatások felsorolása - Page 9',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Bónuszok:',
        services: [
          {
            id: '1',
            title: 'Díjmentes Setup',
            description: 'Díjmentesen átvesszük a fiókot és elvégezzük a szükséges beállításokat',
            icon: '/icons/setup.svg',
            price: '100.000 Ft',
            priceNote: 'Érték',
          },
          {
            id: '2',
            title: 'Fiók Audit',
            description: 'Az optimális induláshoz 2-3 évre visszamenőleg megvizsgáljuk az eddigi hirdetésidet',
            icon: '/icons/audit.svg',
            price: '100.000 Ft',
            priceNote: 'Érték',
          },
          {
            id: '3',
            title: 'Stratégiai tervezés',
            description: 'Az induláshoz és a folytatáshoz is folyamatosan friss stratégiát készítünk neked, amit adatokra alapozva tesztelünk',
            icon: '/icons/strategy.svg',
            price: '75.000 Ft',
            priceNote: 'Érték',
          },
          {
            id: '4',
            title: 'Havi 1 órás riporting',
            description: 'Nem egy dokumentumot küldünk át e-mailen, hanem a kampánymenedzsereddel közösen kielemzitek az adatokat',
            icon: '/icons/reporting.svg',
            price: '20.000 Ft',
            priceNote: 'Érték',
          },
          {
            id: '5',
            title: 'Teljes vevőszerző rendszerre tett javaslatok',
            description: 'Nem csak a kampányokra, hanem a marketing rendszered összes elemére adunk javaslatot, akkor is, ha csak egy fiókot kezelünk',
            icon: '/icons/consultation.svg',
            price: 'Felbecsülhetetlen',
            priceNote: 'Érték',
          },
          {
            id: '6',
            title: 'Stratégiai Partnereink által nyújtott bónuszok',
            description: 'Egyes feladatokra megbízható külsősöket javaslunk, kipróbáltuk mindet, kiválóak.',
            icon: '/icons/partners.svg',
            price: 'Lásd a 15. oldalon',
            priceNote: '',
          },
        ],
        columns: 3,
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 107,
    },
    {
      blockType: BlockType.GUARANTEES,
      name: 'BOOM Garanciák (2-3-4 napos)',
      description: 'A 2-3-4-es garancia és partneri kapcsolat feltételei - Page 10',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Garanciák:',
        subheading: 'A 2-3-4-es garancia:',
        leftColumn: [
          '2 munkanapon belül reagálunk',
          '3 munkanap után, ha nem reagál az ügyfél egy fontos kampányokat érintő kérdésre, akkor a válaszig a legjobb szakmai tudásunk szerint visszük azokat',
          '4 munkanapon belül elvégezzük a kampányokkal kapcsolatban kért módosításokat',
        ],
        centerContent: {
          title: 'A csapatunk arra vállal garanciát, ami 100%-ban rajtunk múlik, ez pedig az általunk beletett munka minősége és a folyamatos kapcsolattartás',
          description: 'A teljes vevőszerző folyamatod fejlesztését úgy garantáljuk, hogy a havi 1 órás riportingon ki fogunk térni erre is.',
        },
        rightColumn: [
          'Partneri kapcsolatban működünk a legjobban:',
          'Kölcsönös tisztelet',
          'Határidők betartása',
          'Eszközök rendelkezésre állása',
          'Tervezünk és nem kapkodunk',
          'Elmondjuk a szakmai véleményünket',
          'Mi is szívesen meghallgatjuk az ötleteket',
        ],
        quote: '"Ha nem nyitod ki az autót, akkor nem tud dolgozni vele a szerelő."',
        centerImage: '/images/boom/guarantees-illustration.png',
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 108,
    },
    {
      blockType: BlockType.PROCESS_TIMELINE,
      name: 'BOOM Közös Munka Folyamata',
      description: 'A közös munka kezdetéig vezető út lépései - Page 11',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'A közös munka kezdetéig vezető út',
        subheading: 'Hogyan tartjuk magasan a minőséget mozgalmas időszakokban is?',
        steps: [
          {
            id: '1',
            title: '2 hetes felkészülés',
            subtitle: 'Felkészülési időszak',
            description: 'Szerződéstervezet átküldése → Szerződés megkötése → Hozzáférések megadása → Fiók auditálása',
          },
          {
            id: '2',
            title: 'Kampánytervezés-technikai setup',
            subtitle: '4 munkanap alatt',
            description: 'Kick-off meeting → Hirdetések aktiválása és elfogadtatása',
          },
          {
            id: '3',
            title: 'Monitorozás és optimalizálás',
            subtitle: 'Folyamatos munka',
            description: 'Minden hónapot követően átbeszéljük az eredményeket tartalmazó kimutatásokat és javaslatokat teszünk a teljes vevőszerző folyamat fejlesztésére',
          },
        ],
        additionalInfo: [
          'Legfeljebb heti 2 új projektet vállalunk be, hogy a már bizalmat szavazott ügyfeleink igényeit teljeskörűen tudjuk teljesíteni',
          'A BOOM kapui évi 11 hónapig nyitottak az új ügyfeleknek, mert decembereben csak a meglévő ügyfeleink kampányait kezeljük',
        ],
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 109,
    },
    {
      blockType: BlockType.PROCESS_TIMELINE,
      name: 'BOOM Első 4 Hónap Ütemterve',
      description: 'Hónapról hónapra bontott fejlődési ütemterv - Page 12',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Az első 4 hónap részletes ütemterve',
        steps: [
          {
            id: '1',
            title: '1. hónap:',
            subtitle: 'Felkészülés és technikai beállítások',
            description: 'Technikai finomhangolások, Összeszokik a csapat, Adatgyűjtés, Tesztelés',
          },
          {
            id: '2',
            title: '2. hónap:',
            subtitle: 'Optimalizálás kezdete',
            description: 'Adatgyűjtés, Optimalizálás, Még több tesztelés',
          },
          {
            id: '3',
            title: '3. hónap:',
            subtitle: 'Skálázás indítása',
            description: 'Kezdődik a skálázás, Tovább optimalizálunk, Még mindig tesztelünk, És adatokat gyűjtünk',
          },
          {
            id: '4',
            title: '4. hónap:',
            subtitle: 'Bővítés és újabb elemek',
            description: 'Adatgyűjtés, Visszamérés, Elemzés, Ötletelés, Optimalizálás, Új elem bevonása a Marketing Ökoszisztémádba',
          },
        ],
        centerImage: '/images/boom/timeline-illustration.png',
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 110,
    },
    {
      blockType: BlockType.SERVICES_GRID,
      name: 'BOOM További Szolgáltatások',
      description: 'Mi mindenben tudunk még segíteni - Page 13',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Mi mindenben tudunk még segíteni?',
        services: [
          {
            id: '1',
            title: 'E-mail Marketing Rendszer',
            description: 'Automatizált e-mail kampányok tervezése és kivitelezése',
            icon: '/icons/email-marketing.svg',
            price: 'Egyedi árajánlat',
          },
          {
            id: '2',
            title: 'Copywriting',
            description: 'Konverzióra optimalizált szövegírás minden felületre',
            icon: '/icons/copywriting.svg',
            price: 'Egyedi árajánlat',
          },
          {
            id: '3',
            title: 'Landing, sales oldalak',
            description: 'Eladásra optimalizált landing és értékesítési oldalak',
            icon: '/icons/landing-page.svg',
            price: 'Egyedi árajánlat',
          },
          {
            id: '4',
            title: 'Teljes vevőszerző Audit',
            description: 'Átfogó elemzés a teljes értékesítési folyamatról',
            icon: '/icons/audit-full.svg',
            price: 'Egyedi árajánlat',
          },
          {
            id: '5',
            title: 'Social media',
            description: 'Közösségi média jelenléted teljes körű kezelése',
            icon: '/icons/social-media.svg',
            price: 'Egyedi árajánlat',
          },
        ],
        columns: 3,
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 111,
    },
    {
      blockType: BlockType.CLIENT_LOGOS,
      name: 'BOOM Partnereink',
      description: 'Velük már volt szerencsénk együtt dolgozni - Page 14',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Velük már volt szerencsénk együtt dolgozni',
        logos: [
          { id: '1', name: 'BESTMARKT', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-bestmarkt.png' },
          { id: '2', name: 'BAMBA MARHA', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-bamba-marha.webp' },
          { id: '3', name: 'BIOBUBI', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-biobubi.png' },
          { id: '4', name: 'LIVING FOODS', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-living-foods.webp' },
          { id: '5', name: 'PIROSKA', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-piroska.png' },
          { id: '6', name: 'OPTIMONK', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-optimonk.webp' },
          { id: '7', name: 'UPDATE', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-update1.png' },
          { id: '8', name: 'PONGOR GROUP', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-pongor-group.png' },
          { id: '9', name: 'WP KURZUS', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-wpkurzus.png' },
          { id: '10', name: 'CÉGESPOLO.EU', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-cegespoloeu.png' },
          { id: '11', name: 'BIZERBA', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-bizerba.webp' },
          { id: '12', name: 'DBH INNOHUB', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-dbh-innohub.png' },
          { id: '13', name: 'SELL AND SPEAK', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-sellandspeak.png' },
          { id: '14', name: 'M-ACRYL', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-m-acryl.webp' },
          { id: '15', name: 'INKNESS', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-inkness.webp' },
          { id: '16', name: 'COCONUT OIL COSMETICS', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-coconut-oil-cosmetics.png' },
          { id: '17', name: 'NEVERLAND', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-neverland.png' },
          { id: '18', name: 'MENEDZSERPRAXIS', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-menedzserpraxis.png' },
          { id: '19', name: 'BEE WELL', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-bee-well.png' },
          { id: '20', name: 'SÁRRÉT CHILIFARM', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-sarreti-chilifarm.png' },
          { id: '21', name: 'PLAZMA CENTRUM', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-plazma-centrum.png' },
          { id: '22', name: 'RADAWAY', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-radaway.webp' },
          { id: '23', name: 'MÁRTOGATÓS', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-martogatos.png' },
          { id: '24', name: 'MAI UTAZÁS', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-maiutazas.png' },
          { id: '25', name: 'EASY BUSINESS', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-easy-business.png' },
          { id: '26', name: 'ZYNTERN', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-zyntern.png' },
          { id: '27', name: 'PETCHEF', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-petchef.png' },
          { id: '28', name: 'ESKÜVŐ CLASSIC', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-eskuvo-classic.webp' },
          { id: '29', name: 'PROGASTRO', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-progastro.png' },
          { id: '30', name: 'ION', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-ion.webp' },
          { id: '31', name: 'VITALSPA', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2025/01/logo-vitalspa.webp' },
          { id: '32', name: 'DUNA ELEKTRONIKA', imageUrl: 'https://boommarketing.hu/wp-content/uploads/2022/01/ugyfellogo-duna-elektronika.png' },
        ],
        columns: 4,
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 112,
    },
    {
      blockType: BlockType.SERVICES_GRID,
      name: 'BOOM Ajánlott Partnerek Kuponfüzet',
      description: 'Őket ajánljuk - BOOM marketing kuponfüzet - Page 15',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Őket ajánljuk!',
        subheading: 'BOOM marketing kuponfüzet',
        services: [
          {
            id: '1',
            title: 'WP Viking Agency',
            description: 'WordPress fejlesztés és karbantartás',
            icon: '/logos/partners/wpviking.png',
            price: 'Kupon elérhető',
          },
          {
            id: '2',
            title: 'Praxis Weben',
            description: 'Weboldalak és webshopok készítése',
            icon: '/logos/partners/praxis-weben.png',
            price: 'Kupon elérhető',
          },
          {
            id: '3',
            title: 'BP Digital',
            description: 'Digitális marketing megoldások',
            icon: '/logos/partners/bp-digital.png',
            price: 'Kupon elérhető',
          },
          {
            id: '4',
            title: 'Everigo International Group',
            description: 'Nemzetközi üzleti tanácsadás',
            icon: '/logos/partners/everigo.png',
            price: 'Kupon elérhető',
          },
          {
            id: '5',
            title: 'Sápi Domán',
            description: 'Üzleti fotózás és branding',
            icon: '/logos/partners/sapi-doman.png',
            price: 'Kupon elérhető',
          },
        ],
        columns: 3,
        email: 'a.istvan@boommarketing.hu',
        note: 'SÁPI DOMÁN',
      },
      displayOrder: 113,
    },
    {
      blockType: BlockType.CTA,
      name: 'BOOM Multi-Platform Előnyök CTA',
      description: 'Miért éri meg más platformokat is kipróbálni - Záró CTA - Page 16',
      brand: Brand.BOOM,
      defaultContent: {
        version: '1.0',
        heading: 'Miért éri meg más platformokat is kipróbálni?',
        description: 'Fedezd fel a Marketing Ökoszisztéma előnyeit több platformon keresztül. Segítünk kiépíteni egy olyan rendszert, ahol az elemek egymást erősítve működnek.',
        primaryCta: {
          text: 'Egyeztessünk',
          url: 'mailto:a.istvan@boommarketing.hu',
        },
        secondaryCta: {
          text: 'Hívj fel most',
          url: 'tel:+36301234567',
        },
        backgroundImage: '/images/boom/cta-bg.jpg',
        backgroundColor: '#fa604a',
        email: 'a.istvan@boommarketing.hu',
      },
      displayOrder: 114,
    },
  ]

  for (const template of blockTemplates) {
    await prisma.blockTemplate.upsert({
      where: {
        blockType_name_brand: {
          blockType: template.blockType,
          name: template.name,
          brand: template.brand,
        },
      },
      update: {
        description: template.description,
        defaultContent: template.defaultContent,
        displayOrder: template.displayOrder,
      },
      create: template,
    })
  }

  console.log('✅ Created block templates')

  // Create a sample proposal
  const sampleProposal = await prisma.proposal.create({
    data: {
      slug: 'pelda-ajanlat-2025',
      clientName: 'Példa Vállalkozás',
      brand: Brand.BOOM,
      status: 'PUBLISHED',
      createdById: admin.id,
      blocks: {
        create: [
          {
            blockType: BlockType.HERO,
            displayOrder: 0,
            content: blockTemplates[0].defaultContent,
            templateId: (await prisma.blockTemplate.findFirst({
              where: { blockType: BlockType.HERO },
            }))?.id,
          },
          {
            blockType: BlockType.PRICING_TABLE,
            displayOrder: 1,
            content: blockTemplates[3].defaultContent,
            templateId: (await prisma.blockTemplate.findFirst({
              where: { blockType: BlockType.PRICING_TABLE },
            }))?.id,
          },
        ],
      },
    },
  })

  console.log('✅ Created sample proposal')

  console.log('🎉 Database seeding completed!')
  console.log(`📧 Admin login: admin@boommarketing.hu / admin123`)
  console.log(`📧 Admin login: admin@aiboost.hu / admin123`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
